DROP TABLE notification IF EXISTS;
DROP TABLE subscription IF EXISTS;
DROP TABLE users IF EXISTS;

CREATE TABLE users
(
  email    VARCHAR(100) PRIMARY KEY,
  password VARCHAR(100) NOT NULL
);
CREATE TABLE subscription
(
  user_email        VARCHAR(100) NOT NULL,
  service_id        VARCHAR(20)  NOT NULL,
  service_name      VARCHAR(100) NOT NULL,
  language_id       VARCHAR(20)  NOT NULL,
  language_name     VARCHAR(100) NOT NULL,
  search_until_date DATE         NOT NULL,
  PRIMARY KEY (user_email, service_id),
  CONSTRAINT subscription_user_email_fk FOREIGN KEY (user_email) REFERENCES users (email)
);
CREATE TABLE notification
(
  id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_email VARCHAR(100) NOT NULL,
  doctor     VARCHAR(100) NOT NULL,
  clinic     VARCHAR(100) NOT NULL,
  service    VARCHAR(100) NOT NULL,
  date_time  DATETIME,
  CONSTRAINT notification_user_email_fk FOREIGN KEY (user_email) REFERENCES users (email)
)
