INSERT INTO USER (EMAIL) VALUES ('test@test.com');
INSERT INTO USER (EMAIL) VALUES ('test2@test.com');
INSERT INTO SUBSCRIPTION (USER_EMAIL, SERVICE_ID, SERVICE_NAME, LANGUAGE_ID, LANGUAGE_NAME, SEARCH_UNTIL_DATE) VALUES
  ('test@test.com', '1', 'Doctor', '1', 'Spanish', to_date('14-02-2018', 'dd-mm-yyyy'));
